const test = require('node:test');
const assert = require('node:assert/strict');
const path = require('node:path');
process.env.LINKSHARE_DB_PATH = path.resolve(__dirname, '..', 'linkshare.test.db');
const { ApiError, ControlPlane } = require('../src/domain');
const database = require('../src/db');
const { createServer } = require('../src/server');
const { issueTurnCredentials } = require('../src/turn');

let testNumber = Date.now();
function setup() { const suffix = String(++testNumber); const hostId = `host-${suffix}`; const clientId = `client-${suffix}`; const hostKey = `host-device-public-key-${suffix}`; const clientKey = `client-device-public-key-${suffix}`; database.insertDevice(hostId, hostKey); database.insertDevice(clientId, clientKey); database.createFriendRequest(hostId, clientId); database.updateFriendStatus(hostId, clientId, 'accepted'); database.createFriendRequest(clientId, hostId); database.updateFriendStatus(clientId, hostId, 'accepted'); return { control: new ControlPlane(database), hostId, clientId, hostKey, clientKey }; }
test('requires host approval before creating a session', () => { const { control, hostId, clientId, clientKey } = setup(); const pending = control.requestAccess(clientId, { hostId, clientPublicKey: clientKey }); assert.equal(pending.state, 'requesting'); const session = control.approveRequest(hostId, pending.id); assert.equal(session.state, 'handshaking'); assert.equal(session.clientId, clientId); assert.equal(database.getSessionById(session.id).status, 'handshaking'); });
test('does not expose a request to another host', () => { const { control, hostId, clientId, clientKey } = setup(); const pending = control.requestAccess(clientId, { hostId, clientPublicKey: clientKey }); assert.throws(() => control.approveRequest('intruder', pending.id), error => error instanceof ApiError && error.code === 'SESSION_NOT_FOUND'); });
test('enforces server-side session transitions', () => { const { control, hostId, clientId, clientKey } = setup(); const pending = control.requestAccess(clientId, { hostId, clientPublicKey: clientKey }); const session = control.approveRequest(hostId, pending.id); assert.equal(control.setSessionState(clientId, session.id, 'connected').state, 'connected'); assert.throws(() => control.setSessionState(clientId, session.id, 'handshaking'), error => error.code === 'INVALID_SESSION_TRANSITION'); });
test('revoked tokens cannot authenticate', () => { const { control, clientId } = setup(); const token = control.issueToken(clientId).accessToken; assert.equal(control.authenticate(token), clientId); control.revokeToken(token); assert.throws(() => control.authenticate(token), error => error.code === 'TOKEN_INVALID'); });
test('persists session bytes and end timestamps', () => { const { control, hostId, clientId, clientKey } = setup(); const pending = control.requestAccess(clientId, { hostId, clientPublicKey: clientKey }); const session = control.approveRequest(hostId, pending.id); database.incrementSessionBytes(session.id, 2048); control.setSessionState(clientId, session.id, 'connected'); const ended = control.setSessionState(clientId, session.id, 'ended'); assert.equal(ended.bytesUsed, 2048); assert.ok(database.getSessionById(session.id).ended_at); });
test('creates the required schema and lookup indexes', () => { const tableNames = database.db.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name IN ('devices', 'friends', 'sessions', 'tokens')").all().map(row => row.name); const indexNames = database.db.prepare("SELECT name FROM sqlite_master WHERE type = 'index' AND name IN ('idx_devices_device_id', 'idx_tokens_token')").all().map(row => row.name); assert.deepEqual(tableNames.sort(), ['devices', 'friends', 'sessions', 'tokens']); assert.deepEqual(indexNames.sort(), ['idx_devices_device_id', 'idx_tokens_token']); });
test('issues short-lived TURN credentials scoped to a device and session', () => { const first = issueTurnCredentials({ sessionId: '7', deviceId: 'client', sharedSecret: 'turn-secret', urls: ['turn:relay.example:3478?transport=udp'], now: () => 0 }); const second = issueTurnCredentials({ sessionId: '7', deviceId: 'host', sharedSecret: 'turn-secret', urls: ['turn:relay.example:3478?transport=udp'], now: () => 0 }); assert.equal(first.username, '900:client:7'); assert.equal(first.expiresAtEpochSeconds, 900); assert.notEqual(first.credential, second.credential); });
test('serves TURN credentials through the approval response', async () => { const { control, hostId, clientId, clientKey } = setup(); const { server } = createServer({ controlPlane: control, turnSharedSecret: 'turn-secret', turnUrls: ['turn:relay.example:3478?transport=udp'] }); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); try { const baseUrl = `http://127.0.0.1:${server.address().port}`; const clientToken = control.issueToken(clientId).accessToken; const hostToken = control.issueToken(hostId).accessToken; const request = await fetch(`${baseUrl}/v1/connection-requests`, { method: 'POST', headers: { authorization: `Bearer ${clientToken}`, 'content-type': 'application/json' }, body: JSON.stringify({ hostId, clientPublicKey: clientKey }) }); const pending = await request.json(); const approval = await fetch(`${baseUrl}/v1/connection-requests/${pending.requestId}/approve`, { method: 'POST', headers: { authorization: `Bearer ${hostToken}` } }); const hostSession = await approval.json(); assert.equal(approval.status, 200); assert.equal(hostSession.clientPublicKey, clientKey); assert.match(hostSession.turnCredentials.username, new RegExp(`:${hostId}:${pending.requestId}$`)); } finally { await new Promise(resolve => server.close(resolve)); } });
test('enrollment requires the server-side enrollment credential', async () => { const { server } = createServer({ enrollmentToken: 'enrollment-secret' }); await new Promise(resolve => server.listen(0, '127.0.0.1', resolve)); try { const baseUrl = `http://127.0.0.1:${server.address().port}`; const denied = await fetch(`${baseUrl}/v1/devices/register`, { method: 'POST' }); assert.equal(denied.status, 401); const accepted = await fetch(`${baseUrl}/v1/devices/register`, { method: 'POST', headers: { 'x-enrollment-token': 'enrollment-secret', 'content-type': 'application/json' }, body: JSON.stringify({ deviceId: 'new-device', publicKey: 'a-real-device-public-key' }) }); assert.equal(accepted.status, 201); assert.ok((await accepted.json()).accessToken); } finally { await new Promise(resolve => server.close(resolve)); } });
