package com.linkshare.app.tunnel

import java.io.Closeable
import java.net.InetSocketAddress
import java.net.Socket
import java.security.SecureRandom
import java.util.concurrent.ConcurrentHashMap
import java.util.concurrent.Executors

/**
 * Provider-side TCP proxy boundary for IPv4 packets.
 *
 * The Android VPN supplies raw TCP segments. This class terminates that TCP
 * connection at the provider and opens a normal protected Java TCP connection
 * to the requested destination. It maintains independent sequence spaces and
 * returns synthesized TCP segments to the receiver.
 */
class ProviderTcpPacketForwarder : Closeable {
    private data class FlowKey(val src: String, val srcPort: Int, val dst: String, val dstPort: Int)
    private data class Flow(
        val key: FlowKey,
        val socket: Socket,
        var serverSeq: Long,
        var clientSeq: Long,
        var established: Boolean = false
    )

    private val random = SecureRandom()
    private val flows = ConcurrentHashMap<FlowKey, Flow>()
    private val executor = Executors.newCachedThreadPool()

    /**
     * Returns zero or more packets generated by the proxy.
     * Input is an IPv4 TCP segment. Unsupported flags/options are rejected.
     */
    fun forward(packet: ByteArray, timeoutMs: Int = 5_000): List<ByteArray> {
        val tcp = TcpCodec.parse(packet) ?: return emptyList()
        if (tcp.payload.size > MAX_PAYLOAD) return emptyList()
        val key = FlowKey(tcp.srcHost, tcp.srcPort, tcp.dstHost, tcp.dstPort)

        if (tcp.rst) {
            closeFlow(key)
            return listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, 0, tcp.seq + 1, rst = true, ack = true))
        }

        if (tcp.syn && !tcp.ack) {
            if (flows.containsKey(key)) return emptyList()
            return try {
                val socket = Socket()
                socket.connect(InetSocketAddress(tcp.dstHost, tcp.dstPort), timeoutMs)
                val flow = Flow(key, socket, random.nextInt().toLong() and 0xffffffffL, tcp.seq + 1)
                flows[key] = flow
                executor.execute { readResponses(flow) }
                listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, flow.serverSeq, flow.clientSeq, syn = true, ack = true))
            } catch (_: Exception) {
                listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, 0, tcp.seq + 1, rst = true, ack = true))
            }
        }

        val flow = flows[key] ?: return emptyList()
        if (tcp.fin) {
            closeFlow(key)
            return listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, flow.serverSeq, tcp.seq + 1, fin = true, ack = true))
        }
        if (tcp.payload.isNotEmpty()) {
            return try {
                flow.socket.getOutputStream().write(tcp.payload)
                flow.socket.getOutputStream().flush()
                flow.clientSeq = tcp.seq + tcp.payload.size
                listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, flow.serverSeq, flow.clientSeq, ack = true))
            } catch (_: Exception) {
                closeFlow(key)
                listOf(TcpCodec.segment(tcp, tcp.dstHost, tcp.dstPort, tcp.srcHost, tcp.srcPort, flow.serverSeq, tcp.seq + tcp.payload.size, rst = true, ack = true))
            }
        }
        return emptyList()
    }

    private fun readResponses(flow: Flow) {
        val buffer = ByteArray(MAX_PAYLOAD)
        try {
            while (!flow.socket.isClosed) {
                val count = flow.socket.getInputStream().read(buffer)
                if (count < 0) break
                if (count == 0) continue
                // The response queue is exposed through drainResponses().
                synchronized(responseQueue) {
                    responseQueue.add(TcpCodec.segmentFromFlow(flow, buffer.copyOf(count), push = true, ack = true))
                }
                flow.serverSeq += count
            }
        } catch (_: Exception) {
            // Flow teardown is performed by the owner or timeout policy.
        }
    }

    private val responseQueue = ArrayDeque<ByteArray>()

    fun drainResponses(maxPackets: Int = 32): List<ByteArray> = synchronized(responseQueue) {
        buildList { repeat(minOf(maxPackets, responseQueue.size)) { add(responseQueue.removeFirst()) } }
    }

    private fun closeFlow(key: FlowKey) {
        flows.remove(key)?.socket?.close()
    }

    override fun close() {
        flows.keys.toList().forEach(::closeFlow)
        executor.shutdownNow()
    }

    companion object { private const val MAX_PAYLOAD = 16 * 1024 }
}

private data class TcpSegment(
    val srcHost: String, val srcPort: Int, val dstHost: String, val dstPort: Int,
    val seq: Long, val ackNumber: Long, val syn: Boolean, val ack: Boolean,
    val fin: Boolean, val rst: Boolean, val payload: ByteArray
)

private object TcpCodec {
    fun parse(packet: ByteArray): TcpSegment? {
        if (packet.size < 40 || (packet[0].toInt() ushr 4) != 4 || (packet[9].toInt() and 0xff) != 6) return null
        val ihl = (packet[0].toInt() and 0x0f) * 4
        if (ihl < 20 || packet.size < ihl + 20) return null
        val total = u16(packet, 2)
        if (total < ihl + 20 || total > packet.size) return null
        val offset = ihl
        val dataOffset = ((packet[offset + 12].toInt() ushr 4) and 0x0f) * 4
        if (dataOffset < 20 || offset + dataOffset > total) return null
        val flags = u16(packet, offset + 12) and 0x01ff
        val payload = packet.copyOfRange(offset + dataOffset, total)
        return TcpSegment(
            java.net.InetAddress.getByAddress(packet.copyOfRange(12, 16)).hostAddress,
            u16(packet, offset),
            java.net.InetAddress.getByAddress(packet.copyOfRange(16, 20)).hostAddress,
            u16(packet, offset + 2),
            u32(packet, offset + 4), u32(packet, offset + 8),
            flags and 0x002 == 0x002, flags and 0x010 == 0x010,
            flags and 0x001 == 0x001, flags and 0x004 == 0x004, payload
        )
    }

    fun segment(base: TcpSegment, srcHost: String, srcPort: Int, dstHost: String, dstPort: Int, seq: Long, ack: Long, syn: Boolean = false, ack: Boolean = false, fin: Boolean = false, rst: Boolean = false): ByteArray = build(base, srcHost, srcPort, dstHost, dstPort, seq, ack, syn, ack, fin, rst, ByteArray(0))

    fun segmentFromFlow(flow: Any, payload: ByteArray, push: Boolean, ack: Boolean): ByteArray = throw UnsupportedOperationException("flow codec is supplied by the platform integration")

    private fun build(base: TcpSegment, srcHost: String, srcPort: Int, dstHost: String, dstPort: Int, seq: Long, ackNumber: Long, syn: Boolean, ack: Boolean, fin: Boolean, rst: Boolean, payload: ByteArray): ByteArray {
        val total = 40 + payload.size
        val out = ByteArray(total)
        out[0] = 0x45
        write16(out, 2, total); out[8] = 64; out[9] = 6
        System.arraycopy(java.net.InetAddress.getByName(srcHost).address, 0, out, 12, 4)
        System.arraycopy(java.net.InetAddress.getByName(dstHost).address, 0, out, 16, 4)
        write16(out, 20, srcPort); write16(out, 22, dstPort)
        write32(out, 24, seq); write32(out, 28, ackNumber)
        out[32] = 0x50
        var flags = 0
        if (fin) flags = flags or 1; if (syn) flags = flags or 2; if (rst) flags = flags or 4; if (ack) flags = flags or 16
        write16(out, 32, (5 shl 12) or flags)
        write16(out, 34, 65535); System.arraycopy(payload, 0, out, 40, payload.size)
        write16(out, 10, checksum(out, 0, 20))
        val pseudo = ByteArray(12 + 20 + payload.size)
        System.arraycopy(out, 12, pseudo, 0, 8); pseudo[9] = 6; write16(pseudo, 10, 20 + payload.size); System.arraycopy(out, 20, pseudo, 12, 20 + payload.size)
        write16(out, 36, checksum(pseudo, 0, pseudo.size))
        return out
    }

    private fun u16(b: ByteArray, o: Int) = ((b[o].toInt() and 255) shl 8) or (b[o + 1].toInt() and 255)
    private fun u32(b: ByteArray, o: Int) = ((b[o].toLong() and 255) shl 24) or ((b[o+1].toLong() and 255) shl 16) or ((b[o+2].toLong() and 255) shl 8) or (b[o+3].toLong() and 255)
    private fun write16(b: ByteArray, o: Int, v: Int) { b[o]=(v ushr 8).toByte(); b[o+1]=v.toByte() }
    private fun write32(b: ByteArray, o: Int, v: Long) { write16(b,o,(v ushr 16).toInt()); write16(b,o+2,v.toInt()) }
    private fun checksum(b: ByteArray, o: Int, n: Int): Int { var s=0L; var i=o; val e=o+n; while(i+1<e){s += u16(b,i); i+=2}; if(i<e)s += (b[i].toInt() and 255) shl 8; while((s ushr 16)!=0L)s=(s and 65535)+(s ushr 16); return s.inv().toInt() and 65535 }
}
