package com.linkshare.app.ui.screens

import androidx.compose.foundation.layout.*
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.linkshare.app.ui.components.*
import com.linkshare.app.ui.theme.*

@Composable fun FriendsScreen(onFindFriends:()->Unit,onFriendTap:()->Unit){Column(Modifier.fillMaxSize().padding(horizontal=16.dp)){Spacer(Modifier.height(8.dp));Text("Friends",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Your LINKO connection network",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(16.dp));LinkoCard{Text("NO FRIENDS YET",color=TextMuted,fontSize=11.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Text("Friends added through LINKO will appear here. No sample accounts are shown.",color=TextSub,fontSize=12.sp,fontFamily=JetBrainsMono)};Spacer(Modifier.weight(1f));PrimaryButton("+ FIND FRIENDS",onFindFriends);Spacer(Modifier.height(24.dp))}}
@Composable fun FindFriendsScreen(onSearch:()->Unit){var query by remember{mutableStateOf("")};Column(Modifier.fillMaxSize().padding(horizontal=16.dp)){Spacer(Modifier.height(8.dp));Text("Find Friends",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Search by LINKO ID",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(20.dp));LinkoInput("SEARCH",query,{query=it},"LNK-XXXXXXXX","Enter a real LINKO device ID");Spacer(Modifier.weight(1f));PrimaryButton("SEARCH",onSearch);Spacer(Modifier.height(24.dp))}}
@Composable fun FriendProfileScreen(onSendRequest:()->Unit){Column(Modifier.fillMaxSize().padding(horizontal=16.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(24.dp));Ring(Blue,120.dp,label="DEVICE");Spacer(Modifier.height(16.dp));Text("LINKO DEVICE",color=TextPrimary,fontSize=20.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("No friend selected",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(28.dp));LinkoCard{InfoRow("STATUS","NOT SELECTED","Search and select a real LINKO device",accent=Yellow)};Spacer(Modifier.weight(1f));PrimaryButton("SEND REQUEST",{},color=TextMuted,outline=true);Spacer(Modifier.height(24.dp))}}
@Composable fun RequestSentScreen(onCancel:()->Unit){Column(Modifier.fillMaxSize().padding(horizontal=16.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.weight(1f));Ring(Yellow,180.dp,pulse=true,label="PENDING",onClick=onCancel);Spacer(Modifier.height(20.dp));Text("Request Sent",color=TextPrimary,fontSize=18.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));Text("Waiting for the selected device to respond",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.weight(1f));PrimaryButton("CANCEL REQUEST",onCancel,color=Red,outline=true);Spacer(Modifier.height(24.dp))}}
@Composable fun IncomingRequestScreen(onAccept:()->Unit,onReject:()->Unit){Column(Modifier.fillMaxSize().padding(horizontal=16.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(8.dp));Text("Incoming Request",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(4.dp));Text("A LINKO device is requesting access",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(28.dp));Ring(Yellow,120.dp,label="REQUEST");Spacer(Modifier.height(20.dp));LinkoCard{InfoRow("REQUEST","Pending","You control whether access is allowed")};Spacer(Modifier.weight(1f));PrimaryButton("ACCEPT",onAccept,color=Green);Spacer(Modifier.height(8.dp));PrimaryButton("REJECT",onReject,color=Red,outline=true);Spacer(Modifier.height(24.dp))}}

@Composable fun BlockedRemovedScreen(onManage:()->Unit){
    var tab by remember { mutableStateOf("BLOCKED") }
    Column(Modifier.fillMaxSize().padding(horizontal=16.dp)){
        Spacer(Modifier.height(8.dp));Text("Trust Boundaries",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Manage devices you have blocked or removed",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(18.dp))
        Row(Modifier.fillMaxWidth()){PrimaryButton("BLOCKED",{tab="BLOCKED"},color=if(tab=="BLOCKED")Blue else TextMuted,outline=tab!="BLOCKED");Spacer(Modifier.width(8.dp));PrimaryButton("REMOVED",{tab="REMOVED"},color=if(tab=="REMOVED")Blue else TextMuted,outline=tab!="REMOVED")}
        Spacer(Modifier.height(14.dp));LinkoCard{if(tab=="BLOCKED"){Text("NO BLOCKED DEVICES",color=TextMuted,fontSize=11.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Text("Devices you block will appear here. No placeholder devices are shown.",color=TextSub,fontSize=12.sp,fontFamily=JetBrainsMono)}else{Text("NO REMOVED DEVICES",color=TextMuted,fontSize=11.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Text("Devices you remove from your friends list will appear here.",color=TextSub,fontSize=12.sp,fontFamily=JetBrainsMono)}}
        Spacer(Modifier.weight(1f));Text("Use the back button to return to Settings.",color=TextMuted,fontSize=10.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(24.dp))
    }
}
