package com.linkshare.app.ui.screens

import android.content.ClipData
import android.content.ClipboardManager
import android.content.Context
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ContentCopy
import androidx.compose.material.icons.filled.Refresh
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.Text
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.linkshare.app.auth.LinkoAuth
import com.linkshare.app.auth.LinkoDeviceIdentity
import com.linkshare.app.network.LinkoDeviceRegistrar
import com.linkshare.app.network.LinkoRuntimeConfig
import com.linkshare.app.ui.components.*
import com.linkshare.app.ui.theme.*
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.withContext

@Composable
fun SettingsScreen(onProfile:()->Unit,onDevices:()->Unit,onFriends:()->Unit,onBlocked:()->Unit,onHistory:()->Unit,onSecurity:()->Unit,onPrivacy:()->Unit,onDataRetention:()->Unit,onDeleteAccount:()->Unit){Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState())){Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.fillMaxWidth().background(Surface).padding(16.dp)){Box(Modifier.size(56.dp).clip(CircleShape).background(Blue.copy(.13f)),contentAlignment=Alignment.Center){Text("L",color=Blue,fontSize=20.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold)};Spacer(Modifier.width(16.dp));Column{Text("LINKO ACCOUNT",color=TextPrimary,fontSize=17.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Text("Authenticated account",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(5.dp));StatusChip("SECURE",Green)}};Column(Modifier.padding(horizontal=16.dp)){SectionLabel("ACCOUNT");LinkoCard{SettingsRow({Text("👤",fontSize=18.sp)},"Profile","Manage your account identity",onClick=onProfile);RowDivider();SettingsRow({Text("📱",fontSize=18.sp)},"Devices","Manage this LINKO device",onClick=onDevices)};SectionLabel("CONNECTIONS");LinkoCard{SettingsRow({Text("👥",fontSize=18.sp)},"Friends","Your real LINKO connections",onClick=onFriends);RowDivider();SettingsRow({Text("🚫",fontSize=18.sp)},"Blocked & Removed","Manage blocked peers",onClick=onBlocked);RowDivider();SettingsRow({Text("🕐",fontSize=18.sp)},"Session History","Your real sessions only",onClick=onHistory)};SectionLabel("SECURITY & PRIVACY");LinkoCard{SettingsRow({Text("🔒",fontSize=18.sp)},"Security Engine","Connection protection",onClick=onSecurity);RowDivider();SettingsRow({Text("🛡",fontSize=18.sp)},"Privacy","Connection privacy controls",onClick=onPrivacy);RowDivider();SettingsRow({Text("🗑",fontSize=18.sp)},"Data Retention","Control stored session information",onClick=onDataRetention)};Spacer(Modifier.height(8.dp));PrimaryButton("DELETE ACCOUNT",onDeleteAccount,color=Red,outline=true);Spacer(Modifier.height(24.dp))}}}

@Composable
fun DeviceIdentityScreen(onManage:()->Unit){val context=LocalContext.current;val identity=remember{LinkoDeviceIdentity()};val auth=remember{LinkoAuth(context)};val scope=rememberCoroutineScope();var fingerprint by remember{mutableStateOf(identity.deviceFingerprint())};var copied by remember{mutableStateOf(false)};var rotating by remember{mutableStateOf(false)};var status by remember{mutableStateOf<String?>(null)}
 fun copyId(){val cb=context.getSystemService(Context.CLIPBOARD_SERVICE) as ClipboardManager;cb.setPrimaryClip(ClipData.newPlainText("LINKO Device ID","LNK-$fingerprint"));copied=true;status="Device ID copied."}
 Column(Modifier.fillMaxSize().verticalScroll(rememberScrollState()).padding(16.dp)){Text("Device Identity",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Your unique LINKO device identifier",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(20.dp));LinkoCard{Text("LINKO DEVICE ID",color=TextMuted,fontSize=10.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(8.dp));Row(verticalAlignment=Alignment.CenterVertically){Text("LNK-$fingerprint",color=Blue,fontSize=18.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold,modifier=Modifier.weight(1f));IconButton(onClick={copyId()}){Icon(Icons.Filled.ContentCopy,"Copy device ID",tint=Blue)}};Text(if(copied)"COPIED" else "Use this ID when connecting with a friend",color=if(copied)Green else TextSub,fontSize=10.sp,fontFamily=JetBrainsMono)};Spacer(Modifier.height(10.dp));LinkoCard{InfoRow("DEVICE", "LINKO READY", "This identifier belongs to this installation",accent=Green)};Spacer(Modifier.height(10.dp));LinkoCard{Text("ROTATE DEVICE ID",color=Yellow,fontSize=10.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(6.dp));Text("Generate a fresh LINKO device identifier. Your previous device session will be cleared.",color=TextSub,fontSize=11.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(12.dp));Row(verticalAlignment=Alignment.CenterVertically,modifier=Modifier.clip(RoundedCornerShape(12.dp)).background(Yellow.copy(.08f)).padding(4.dp)){IconButton(enabled=!rotating,onClick={rotating=true;status=null;scope.launch{val result=runCatching{withContext(Dispatchers.IO){identity.rotate();auth.clearLinkoSession();if(LinkoRuntimeConfig.isConfigured()&&auth.isSignedIn())LinkoDeviceRegistrar(LinkoRuntimeConfig.controlPlaneUrl,auth).ensureRegistered();identity.deviceFingerprint()}};result.onSuccess{fingerprint=it;status="Device ID rotated successfully."}.onFailure{status="Could not rotate device ID."};rotating=false}}){Icon(Icons.Filled.Refresh,"Rotate device ID",tint=Yellow)};Text(if(rotating)"ROTATING…" else "ROTATE ID",color=Yellow,fontSize=11.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold)}};status?.let{Spacer(Modifier.height(10.dp));Text(it,color=if(it.startsWith("Could"))Red else Green,fontSize=11.sp,fontFamily=JetBrainsMono)};Spacer(Modifier.height(24.dp));PrimaryButton("DONE",onManage);Spacer(Modifier.height(24.dp))}}

@Composable fun SecurityEngineScreen(onHome:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp),horizontalAlignment=Alignment.CenterHorizontally){Spacer(Modifier.height(8.dp));Text("Security Engine",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(4.dp));Text("How LINKO protects sessions",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono,modifier=Modifier.fillMaxWidth());Spacer(Modifier.height(24.dp));Ring(Green,160.dp,label="SECURE",onClick=onHome);Spacer(Modifier.height(24.dp));LinkoCard{InfoRow("TUNNEL","Encrypted","Short-lived credentials",accent=Green)};Spacer(Modifier.height(10.dp));LinkoCard{InfoRow("DEVICE","Protected","Session identity stays on this device",accent=Blue)};Spacer(Modifier.weight(1f))}}
@Composable fun PrivacyScreen(onManageData:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Privacy",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Connection privacy controls",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(20.dp));LinkoCard{InfoRow("BROWSING CONTENTS","Not retained","LINKO minimizes data collection",accent=Green)};Spacer(Modifier.height(10.dp));LinkoCard{InfoRow("SESSION METADATA","Limited retention","Used for security and usage",accent=Yellow)};Spacer(Modifier.weight(1f));PrimaryButton("MANAGE DATA",onManageData);Spacer(Modifier.height(24.dp))}}
@Composable fun DataRetentionScreen(onDone:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Data Retention",color=TextPrimary,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("Control stored session information",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(20.dp));LinkoCard{InfoRow("HISTORY","Your sessions","Review or delete session history")};Spacer(Modifier.height(10.dp));LinkoCard{InfoRow("ACCOUNT DATA","Your identity","Delete account permanently")};Spacer(Modifier.weight(1f));PrimaryButton("CLEAR SESSION HISTORY",{},color=Red,outline=true);Spacer(Modifier.height(4.dp));GhostButton("Done",onDone);Spacer(Modifier.height(24.dp))}}
@Composable fun DeleteAccountScreen(onDelete:()->Unit,onCancel:()->Unit){Column(Modifier.fillMaxSize().padding(16.dp)){Text("Delete Account",color=Red,fontSize=22.sp,fontFamily=JetBrainsMono,fontWeight=FontWeight.Bold);Spacer(Modifier.height(4.dp));Text("This action is permanent and irreversible",color=TextSub,fontSize=13.sp,fontFamily=JetBrainsMono);Spacer(Modifier.height(24.dp));LinkoCard{Text("Before deleting, LINKO will clear your account session and local device data.",color=TextPrimary,fontSize=13.sp,fontFamily=JetBrainsMono)};Spacer(Modifier.weight(1f));PrimaryButton("PERMANENTLY DELETE ACCOUNT",onDelete,color=Red);Spacer(Modifier.height(4.dp));GhostButton("Cancel, keep my account",onCancel);Spacer(Modifier.height(24.dp))}}
