package com.linkshare.app.security

import android.content.Context
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import java.security.KeyStore
import javax.crypto.Cipher
import javax.crypto.KeyGenerator
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec

/**
 * LinkoKeyManager
 *
 * Manages cryptographic keys using the Android Keystore system.
 * On devices with hardware security modules (API 28+, StrongBox), keys
 * are stored in tamper-resistant hardware. On all other devices, keys
 * are stored in the TEE (Trusted Execution Environment).
 *
 * Keys managed here are NEVER exported to memory in raw form.
 * Encryption/decryption happens inside the Keystore.
 */
object LinkoKeyManager {

    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val GCM_TAG_LENGTH_BITS = 128
    private const val GCM_IV_LENGTH_BYTES = 12

    // Key aliases — these are stable identifiers for the Android Keystore
    const val KEY_ALIAS_IDENTITY = "linko_identity_v1"
    const val KEY_ALIAS_SESSION_PREFIX = "linko_session_"

    /**
     * Generate an AES-256-GCM key in the Android Keystore.
     * If a key with this alias already exists, the existing key is used.
     */
    fun getOrCreateKey(alias: String): SecretKey {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }

        if (keyStore.containsAlias(alias)) {
            return (keyStore.getEntry(alias, null) as KeyStore.SecretKeyEntry).secretKey
        }

        val keyGen = KeyGenerator.getInstance(KeyProperties.KEY_ALGORITHM_AES, KEYSTORE_PROVIDER)
        keyGen.init(
            KeyGenParameterSpec.Builder(
                alias,
                KeyProperties.PURPOSE_ENCRYPT or KeyProperties.PURPOSE_DECRYPT
            )
                .setBlockModes(KeyProperties.BLOCK_MODE_GCM)
                .setEncryptionPaddings(KeyProperties.ENCRYPTION_PADDING_NONE)
                .setKeySize(256)
                .setRandomizedEncryptionRequired(true)
                // No user authentication required — keys must work in background service
                .setUserAuthenticationRequired(false)
                .build()
        )
        return keyGen.generateKey()
    }

    /**
     * Encrypt data using the specified Keystore key.
     * Returns IV + ciphertext concatenated (IV is prepended for storage).
     */
    fun encrypt(alias: String, plaintext: ByteArray): ByteArray {
        val key = getOrCreateKey(alias)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // Randomly generated by Keystore
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext  // Prepend IV (12 bytes) to ciphertext
    }

    /**
     * Decrypt data using the specified Keystore key.
     * Input must be IV (12 bytes) + ciphertext (as produced by [encrypt]).
     */
    fun decrypt(alias: String, ivAndCiphertext: ByteArray): ByteArray {
        if (ivAndCiphertext.size <= GCM_IV_LENGTH_BYTES) {
            throw IllegalArgumentException("Input too short to contain IV + ciphertext")
        }
        val key = getOrCreateKey(alias)
        val iv = ivAndCiphertext.copyOfRange(0, GCM_IV_LENGTH_BYTES)
        val ciphertext = ivAndCiphertext.copyOfRange(GCM_IV_LENGTH_BYTES, ivAndCiphertext.size)
        val cipher = Cipher.getInstance("AES/GCM/NoPadding")
        cipher.init(Cipher.DECRYPT_MODE, key, GCMParameterSpec(GCM_TAG_LENGTH_BITS, iv))
        return cipher.doFinal(ciphertext)
    }

    /**
     * Delete a key from the Keystore (e.g. on sign-out or device revocation).
     */
    fun deleteKey(alias: String) {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        if (keyStore.containsAlias(alias)) {
            keyStore.deleteEntry(alias)
        }
    }

    /**
     * Delete all Linko keys from the Keystore (full sign-out / factory reset).
     */
    fun deleteAllLinkoKeys() {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        keyStore.aliases().toList()
            .filter { it.startsWith("linko_") }
            .forEach { keyStore.deleteEntry(it) }
    }

    /**
     * Check if a key exists in the Keystore.
     */
    fun hasKey(alias: String): Boolean {
        val keyStore = KeyStore.getInstance(KEYSTORE_PROVIDER).apply { load(null) }
        return keyStore.containsAlias(alias)
    }
}
