realm=linkshare.local
fingerprint
lt-cred-mech
use-auth-secret
stale-nonce
no-multicast-peers
no-loopback-peers
no-cli
no-tls
no-dtls
listening-port=3478
min-port=49160
max-port=49200
log-file=stdout
simple-log
